### ISSUE TITLE
its not working yet

### ISSUE THREAD

**Issue by hackernm99** [ashawe/Safana#10]
W/hstudios.safan: Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/hstudios.safan: Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
W/Firestore: (0.6.6-dev) [Firestore]: Listen for Query(Employees/SUP001) failed: Status{code=PERMISSION_DENIED, description=Missing or insufficient permissions., cause=null}

**Comment by ashawe** [comment]
This has to do with the firebase setup and permissions you use.

Since firebase has updated the way their system works, you might face this issue. You need to properly read firebase's documentation.

For more info you can visit this [Stackoverflow post](https://stackoverflow.com/questions/46590155/firestore-permission-denied-missing-or-insufficient-permissions)
